const UserActionTypes = {
    SET_CURRENT_USER: 'SET_CURRENT_USER',
    GOOGLE_SIGN_IN_START: 'GOOGLE_SIGN_IN_START',
    EMAIL_SIGN_IN_START: 'EMAIL_SIGN_IN_START',
    SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
    SIGN_IN_FAILURE: 'SIGN_IN_FAILURE',
    CHECK_USER_SESSION: 'CHECK_USER_SESSION',
    SIGN_OUT_START: 'SIGN_OUT_START',
    SIGN_OUT_SUCCESS: 'SIGN_OUT_SUCCESS',
    SIGN_OUT_FAILURE: 'SIGN_OUT_FAILURE',
    SIGN_UP_START: 'SIGN_UP_START',
    SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
    SIGN_UP_FAILURE: 'SIGN_UP_FAILURE',
    SEND_EMAIL_VERIFY_START: 'SEND_EMAIL_VERIFY_START',
    SEND_EMAIL_VERIFY_SUCCESS: 'SEND_EMAIL_VERIFY_SUCCESS',
    SEND_EMAIL_VERIFY_FAILURE: 'SEND_EMAIL_VERIFY_FAILURE',
    SEND_PASSWORD_RESET_START: 'SEND_PASSWORD_RESET_START',
    SEND_PASSWORD_RESET_SUCCESS: 'SEND_PASSWORD_RESET_SUCCESS',
    SEND_PASSWORD_RESET_FAILURE: 'SEND_PASSWORD_RESET_FAILURE',
    UPDATE_USER_START: 'UPDATE_USER_START',
    UPDATE_USER_SUCCESS: 'UPDATE_USER_SUCCESS',
    UPDATE_USER_FAILURE: 'UPDATE_USER_FAILURE',
    GET_USER_UPDATE_START: 'GET_USER_UPDATE_START',
    GET_USER_UPDATE_SUCCESS: 'GET_USER_UPDATE_SUCCESS',
    GET_USER_UPDATE_FAILURE: 'GET_USER_UPDATE_FAILURE',
  };
  
  export default UserActionTypes;
  