const EventActionTypes = {
    GET_EVENTS_START: 'GET_EVENTS_START',
    GET_EVENTS_SUCCESS: 'GET_EVENTS_SUCCESS',
    GET_EVENTS_FAILURE: 'GET_EVENTS_FAILURE',
    GET_NOTIFICATIONS_START: 'GET_NOTIFICATIONS_START',
    GET_NOTIFICATIONS_SUCCESS: 'GET_NOTIFICATIONS_SUCCESS',
    GET_NOTIFICATIONS_FAILURE: 'GET_NOTIFICATIONS_FAILURE',
    CLEAR_NOTIFICATIONS_START: 'CLEAR_NOTIFICATIONS_START',
    CLEAR_NOTIFICATIONS_SUCCESS: 'CLEAR_NOTIFICATIONS_SUCCESS',
    CLEAR_NOTIFICATIONS_FAILURE: 'CLEAR_NOTIFICATIONS_FAILURE',
    EVENT_REGISTER_START: 'EVENT_REGISTER_IN_START',
    EVENT_REGISTER_SUCCESS: 'EVENT_REGISTER_SUCCESS',
    EVENT_REGISTER_FAILURE: 'EVENT_REGISTER_FAILURE',
    GIFT_REGISTER_START: 'GIFT_REGISTER_IN_START',
    GIFT_REGISTER_SUCCESS: 'GIFT_REGISTER_SUCCESS',
    GIFT_REGISTER_FAILURE: 'GIFT_REGISTER_FAILURE',
    PAYOUT_START: 'PAYOUT_START',
    PAYOUT_SUCCESS: 'PAYOUT_SUCCESS',
    PAYOUT_FAILURE: 'PAYOUT_FAILURE',
  };
  
  export default EventActionTypes;
  