const ProductStoreActionTypes = {
    GET_PRODUCTSTORE_START: 'GET_PRODUCTSTORE_START',
    GET_PRODUCTSTORE_SUCCESS: 'GET_PRODUCTSTORE_SUCCESS',
    GET_PRODUCTSTORE_FAILURE: 'GET_PRODUCTSTORE_FAILURE',
    GET_NOTIFICATIONS_START: 'GET_NOTIFICATIONS_START',
    GET_NOTIFICATIONS_SUCCESS: 'GET_NOTIFICATIONS_SUCCESS',
    GET_NOTIFICATIONS_FAILURE: 'GET_NOTIFICATIONS_FAILURE',
    CLEAR_NOTIFICATIONS_START: 'CLEAR_NOTIFICATIONS_START',
    CLEAR_NOTIFICATIONS_SUCCESS: 'CLEAR_NOTIFICATIONS_SUCCESS',
    CLEAR_NOTIFICATIONS_FAILURE: 'CLEAR_NOTIFICATIONS_FAILURE',
    PRODUCTSTORE_REGISTER_START: 'PRODUCTSTORE_REGISTER_START',
    PRODUCTSTORE_REGISTER_SUCCESS: 'PRODUCTSTORE_REGISTER_SUCCESS',
    PRODUCTSTORE_REGISTER_FAILURE: 'PRODUCTSTORE_REGISTER_FAILURE',
    PRODUCT_REGISTER_START: 'PRODUCT_REGISTER_START',
    PRODUCT_REGISTER_SUCCESS: 'PRODUCT_REGISTER_SUCCESS',
    PRODUCT_REGISTER_FAILURE: 'PRODUCT_REGISTER_FAILURE',

    REGISTER_SUBACC_START: 'REGISTER_SUBACC_START',
    REGISTER_SUBACC_SUCCESS: 'REGISTER_SUBACC_SUCCESS',
    REGISTER_SUBACC_FAILURE: 'REGISTER_SUBACC_FAILURE',

    GET_PURCHASES_START: 'GET_PURCHASES_START',
    GET_PURCHASES_SUCCESS: 'GET_PURCHASES_SUCCESS',
    GET_PURCHASES_FAILURE: 'GET_PURCHASES_FAILURE',

    GIFT_REGISTER_START: 'GIFT_REGISTER_IN_START',
    GIFT_REGISTER_SUCCESS: 'GIFT_REGISTER_SUCCESS',
    GIFT_REGISTER_FAILURE: 'GIFT_REGISTER_FAILURE',
    PAYOUT_START: 'PAYOUT_START',
    PAYOUT_SUCCESS: 'PAYOUT_SUCCESS',
    PAYOUT_FAILURE: 'PAYOUT_FAILURE',
  };
  
  export default ProductStoreActionTypes;
  